### ISSUE TITLE
Crashing instead of adding to collections

### ISSUE THREAD

**Issue by kopiezzo** [steveharsant/edcm#5]
Hey, getting this error when trying to use it:

> 2024-06-09 14:34:39.863 | INFO     | __main__:<module>:73 - Starting EDCM
> 2024-06-09 14:34:39.863 | SUCCESS  | __main__:<module>:76 - Config watcher registered
> 2024-06-09 14:34:39.864 | SUCCESS  | functions:load_config:45 - Found collection rule sets: Netflix
> 2024-06-09 14:34:39.864 | INFO     | __main__:main:18 - Requesting library information
> 2024-06-09 14:34:39.868 | INFO     | __main__:main:23 - Processing 'Netflix' collection rule set
> 2024-06-09 14:34:39.931 | SUCCESS  | __main__:main:58 - Processed items. 21 matches found
> Traceback (most recent call last):
>   File "/app/app.py", line 83, in <module>
>     main(config)
>   File "/app/app.py", line 66, in main
>     if emby_api.update_collection(rule_set, ids):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/api.py", line 44, in update_collection
>     if DEBUG is True:
> 
>        ^^^^^
> NameError: name 'DEBUG' is not defined

This is my docker compose:

> version: '3.8'
> services:
>   edcm:
>     container_name: edcm
>     image: ghcr.io/steveharsant/edcm:latest
>     environment:
>       - EMBY_ADDRESS=192.168.0.xx
>       - EMBY_TOKEN=xx
>     volumes:
>       - /home/lk/docker/edcm:/config
>     restart: unless-stopped
>     labels:
>       - com.centurylinklabs.watchtower.enable=true

My config is just:

> [Netflix]
> Studios = Netflix

**Comment by steveharsant** [comment]
Thanks for flagging. What version is the docker image that you are using? I think in 0.3.0 this _should_ be fixed. 

Unfortunately,  I don't have access to my laptop for a couple of days, but I can look into it more shortly.

As a workaround, I  if you set the EDCM_DEBUG envvar to True. I think this will get things working again.

Let me know how you go 😃

**Comment by kopiezzo** [comment]
Thanks for the quick answer! Unfortunately, setting debug to true doesn't help. I'm not quite sure how to use the 0.3.0 branch; I believe I'm on 0.2.1 (latest), and setting 0.3.0 manually in Docker does not find the manifest

Here's the log with debug enabled:

> 2024-06-10 11:27:01.871 | DEBUG    | functions:debug:10 - Matched 0 of 1 rules to Ratatouille (2007). Matched rules: []
> 2024-06-10 11:27:01.871 | SUCCESS  | __main__:main:58 - Processed items. 21 matches found
> Traceback (most recent call last):
>   File "/app/app.py", line 83, in <module>
>     main(config)
>   File "/app/app.py", line 66, in main
>     if emby_api.update_collection(rule_set, ids):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/api.py", line 44, in update_collection
>     if DEBUG is True:
> 
>        ^^^^^
> NameError: name 'DEBUG' is not defined
